name = "swarlok"
main = "workers.js"
compatibility_date = "2024-04-05"

[site]
bucket = "."
include = ["index.html", "assets/**/*"] # Explicitly tell it to include your HTML

[[kv_namespaces]]
binding = "MUSIC_META"
id = "2d0d2676da544d23a131bcd514c1a28c"

[[r2_buckets]]
binding = "MUSIC_BUCKET"
bucket_name = "music-bucket"