name = "swarlok"
main = "workers.js"
compatibility_date = "2026-04-05"

# THIS IS THE MISSING PIECE
[site]
bucket = "./"

[[kv_namespaces]]
binding = "MUSIC_META"
id = "2d0d2676da544d23a131bcd514c1a28c"

[[r2_buckets]]
binding = "MUSIC_BUCKET"
bucket_name = "music-bucket"